INSERT INTO role (name_fa, name_en) VALUES
('بازیگر', 'Actor'),
('بازیگر زن', 'Actress'),
('کارگردان', 'Director'),
('دستیار کارگردان', 'Assistant Director'),
('نویسنده', 'Writer'),
('فیلمنامه‌نویس', 'Screenwriter'),
('نویسنده داستان', 'Story Writer'),
('تهیه‌کننده', 'Producer'),
('تهیه‌کننده اجرایی', 'Executive Producer'),
('تهیه‌کننده همکار', 'Co-Producer'),
('فیلمبردار', 'Cinematographer'),
('مدیر فیلمبرداری', 'Director of Photography'),
('اپراتور دوربین', 'Camera Operator'),
('تدوینگر', 'Editor'),
('دستیار تدوین', 'Assistant Editor'),
('آهنگساز', 'Composer'),
('مدیر موسیقی', 'Music Supervisor'),
('طراح صدا', 'Sound Designer'),
('تدوینگر صدا', 'Sound Editor'),
('هنرمند افکت‌های صوتی', 'Foley Artist'),
('طراح تولید', 'Production Designer'),
('طراح لباس', 'Costume Designer'),
('هنرمند گریم', 'Makeup Artist'),
('دکوراتور صحنه', 'Set Decorator'),
('سرپرست جلوه‌های ویژه', 'Visual Effects Supervisor'),
('هنرمند افکت‌های ویژه', 'VFX Artist'),
('سرپرست انیمیشن', 'Animation Supervisor'),
('شورانر', 'Showrunner'),
('سازنده', 'Creator'),
('مدیر انتخاب بازیگر', 'Casting Director'),
('مدیر مکان‌یابی', 'Location Manager'),
('هماهنگ‌کننده بدلکاری', 'Stunt Coordinator'),
('سرپرست فیلمنامه', 'Script Supervisor'),
('راوی', 'Narrator'),
('صداپیشه', 'Voice Actor');